# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3d21d6fcb3123b94dddd3dc1d2f4e446"
name = "international-marketplace-app"
handle = "international-marketplace-app-4"
application_url = "https://fitting-already-ids-builder.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-ca1fef80.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_draft_orders,read_orders,write_draft_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://fitting-already-ids-builder.trycloudflare.com/auth/callback",
  "https://fitting-already-ids-builder.trycloudflare.com/auth/shopify/callback",
  "https://fitting-already-ids-builder.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
